# Generated by Django 4.2.7 on 2023-12-12 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_postmodel_author'),
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthorModel',
        ),
    ]
